twitter_app/urls.py
from django.urls import path
from . import views

app_name = 'twitter_app'

urlpatterns = [
    path('', views.home, name='home'),
    path("new_tweet/", views.create_tweet, name="create_tweet"),
]

twitter_git/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('twitter_app.urls')),
    path('accounts/', include('allauth.urls')),
]

twitter_app/models.py
from django.db import models


# Create your models here.

class Tweet(models.Model):
    text = models.TextField()
    date_published = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

twitter_app/forms.py
from django.forms import ModelForm
from .models import Tweet


class TweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = "__all__"

twitter_app/views.py
from django.shortcuts import render, redirect
from .forms import TweetForm
from .models import Tweet


# Create your views here.
def home(request):
    tweets = Tweet.objects.all()

    context = {"tweets": tweets}
    return render(request, 'twitter_app/homepage.html', context)


def create_tweet(request):
    if request.method != "POST":
        form = TweetForm()
    else:
        form = TweetForm(data=request.POST)

        if form.is_valid():
            form.save()
            return redirect("twitter_app:home")

    context = {"form": form}
    return render(request, "twitter_app/new_tweet.html", context)

twitter_app/templates/twitter_app/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static "styles/homepage.css" %}">
</head>
<body>
<div class="container">
            <div class="divider">
            <div id="main-header">
                <ul>
                    <li><a href="#">Homepage</a></li>
                    <li><a href="#">My Tweets</a></li>
                    <li><a href="#">Our Regulation</a></li>
                </ul>
            </div>
                <input type="search" placeholder="&#128269; search Twitter"/>
            </div>
{% block content %}
    <h2>Today's Tweets</h2>
    {% for tweet in tweets %}
        <h4>{{ tweet.text }} <small>Date added: {{ tweet.date_published }}<br></small></h4>

    {% endfor %}
{% endblock %}
</div>
</body>
</html>

twitter_app/templates/twitter_app/new_tweet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static "styles/new_tweet.css" %}">
</head>
<body>
{% block content %}
<div class="container">
    <div class="form">
        {% for new_tweet in form %}
             <form action="{% url 'twitter_app:create_tweet' %}" method="post">

                {% csrf_token %}
                {{ form.as_p }}
                <div class="button-place">
                <button name="submit">Tweet</button>
                </div>
            </form>

        {% endfor %}
    </div>
</div>
{% endblock %}
</body>
</html>